-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN_OPS', 'ADMIN_FINANCE', 'ADMIN_SUPPORT', 'SUPER_ADMIN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'USER';
